# example config
decorator:
  artifact_download_max_retries: 3
  artifact_download_retry_delay: 2
server:
  port: 3000
  rate_limit: 3
  api_key: <strong_token_from_env>
  supported_formats: ['*']
gitlab_client:
  ip: 127.0.0.1
  host: gitlab.example.com
  timeout_seconds: 30
parser:
  sca:
    vuln_mgmt_project_url_tmpl: https://vuln-mgmt.example.com/project/%s/
    vuln_instance_tmpl: example
    report_path: project-1/report
  sast:
    vuln_mgmt_project_url_tmpl: https://fortify-ssc.example.com/html/ssc/version/%d
    vuln_instance_tmpl: audit?q=instance_id%3A
    report_path: audit?q=analysis_type%3Asca
  registered_parsers: